version: '3'

services:
  database:
    container_name: database
    image: "mysql:5.7"
    restart: always
    ports:
      - "3306:3306"
    environment:
        # - MYSQL_HOST=database
        - MYSQL_ROOT_PASSWORD=nodejs
        - MYSQL_DATABASE=database
        - MYSQL_USER=user
        - MYSQL_PASSWORD=passwd
    volumes:
      - /var/lib/mysql
      - ./mysql/migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped

  node-app:
    container_name: node-app
    build: .
    depends_on:
      - database
    ports:
      - "3000:3000"
    links:
      - database:database  
    volumes:
      - .:/usr/src/  
